CREATE TABLE `CLASS` (
	`SUBJECT_CD`	MEDIUMINT(8)	NOT NULL	COMMENT '과목 코드 및 분반 표시',
	`WEEK`	CHAR(3)	NOT NULL	COMMENT '요일',
	`SUBJECT_NM`	VARCHAR(100)	NOT NULL	COMMENT '과목명',
	`PROFESSOR`	VARCHAR(50)	NOT NULL	COMMENT '교수님 성함',
	`START`	CHAR(2)	NOT NULL	COMMENT '시작교시(1A, 1B 등등)',
	`TIME`	MEDIUMINT(8)	NOT NULL	COMMENT '얼마동안 하는가?',
	`CREDITS`	MEDIUMINT(8)	NOT NULL	COMMENT '학점',
	`PASS`	TINYINT(3)	NOT NULL	COMMENT '패논패 과목인지 여부'
);

CREATE TABLE `CLASSROOM` (
	`CODE`	MEDIUMINT(8)	NOT NULL	COMMENT '교실 고유 번호',
	`NAME`	VARCHAR(50)	NOT NULL	COMMENT '교실이름'
);

CREATE TABLE `CLASSROOM USAGE` (
	`WEEK`	CHAR(3)	NOT NULL	COMMENT '요일',
	`CLASSROOM_CD`	MEDIUMINT(8)	NOT NULL	COMMENT '교실 고유 번호',
	`SUBJECT_CD`	MEDIUMINT(8)	NOT NULL	COMMENT '과목 코드 및 분반 표시'
);

CREATE TABLE `USER` (
	`ID`	VARCHAR(16)	NOT NULL	COMMENT '아이디',
	`PWD`	VARCHAR(20)	NOT NULL	COMMENT '비밀번호'
);

CREATE TABLE `TIMETABLE` (
	`ID`	VARCHAR(16)	NOT NULL	COMMENT '아이디',
	`WEEK`	CHAR(3)	NOT NULL	COMMENT '요일',
	`SUBJECT_CD`	MEDIUMINT(8)	NOT NULL	COMMENT '과목 코드 및 분반 표시'
);

ALTER TABLE `CLASS` ADD CONSTRAINT `PK_CLASS` PRIMARY KEY (
	`SUBJECT_CD`,
	`WEEK`
);

ALTER TABLE `CLASSROOM` ADD CONSTRAINT `PK_CLASSROOM` PRIMARY KEY (
	`CODE`
);

ALTER TABLE `CLASSROOM USAGE` ADD CONSTRAINT `PK_CLASSROOM USAGE` PRIMARY KEY (
	`WEEK`,
	`CLASSROOM_CD`,
	`SUBJECT_CD`
);

ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`ID`,
	`PWD`
);

ALTER TABLE `TIMETABLE` ADD CONSTRAINT `PK_TIMETABLE` PRIMARY KEY (
	`ID`,
	`WEEK`,
	`SUBJECT_CD`
);

ALTER TABLE `CLASSROOM USAGE` ADD CONSTRAINT `FK_CLASS_TO_CLASSROOM USAGE_1` FOREIGN KEY (
	`WEEK`
)
REFERENCES `CLASS` (
	`WEEK`
);

ALTER TABLE `CLASSROOM USAGE` ADD CONSTRAINT `FK_CLASS_TO_CLASSROOM USAGE_2` FOREIGN KEY (
	`SUBJECT_CD`
)
REFERENCES `CLASS` (
	`SUBJECT_CD`
);

ALTER TABLE `CLASSROOM USAGE` ADD CONSTRAINT `FK_CLASSROOM_TO_CLASSROOM USAGE_1` FOREIGN KEY (
	`CLASSROOM_CD`
)
REFERENCES `CLASSROOM` (
	`CODE`
);

ALTER TABLE `TIMETABLE` ADD CONSTRAINT `FK_USER_TO_TIMETABLE_1` FOREIGN KEY (
	`ID`
)
REFERENCES `USER` (
	`ID`
);

ALTER TABLE `TIMETABLE` ADD CONSTRAINT `FK_CLASS_TO_TIMETABLE_1` FOREIGN KEY (
	`WEEK`
)
REFERENCES `CLASS` (
	`WEEK`
);

ALTER TABLE `TIMETABLE` ADD CONSTRAINT `FK_CLASS_TO_TIMETABLE_2` FOREIGN KEY (
	`SUBJECT_CD`
)
REFERENCES `CLASS` (
	`SUBJECT_CD`
);

